[versions]
junit = "5.10.2"
assertj = "3.25.3"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[bundles]
testing = ["junit-jupiter", "assertj-core"]
